#!/bin/bash
echo "============================================"
echo "  MITM Purple Team - Blue Team Monitor"
echo "  Tesis Maestría Seguridad Digital - UdelaR"
echo "============================================"
echo ""
echo "Herramientas disponibles:"
echo "  - Suricata IDS 6.0.4"
echo "  - Evidencia de tráfico: /opt/evidence.pcap"
echo "  - Reglas MITM: /etc/suricata/rules/mitm_detection.rules"
echo ""
echo "Flujo de análisis:"
echo "  1. Analizar pcap: suricata -r /opt/evidence.pcap -c /etc/suricata/suricata.yaml -l /tmp/suricata_out/ -k none"
echo "  2. Ver alertas:   cat /tmp/suricata_out/fast.log"
echo "  3. Obtener flags: bash /opt/check_blue_http.sh"
echo "                    bash /opt/check_blue_dns.sh"
echo "                    bash /opt/check_blue_arp.sh"
echo ""
